<br /><br />
<div style="padding-left: 20%">
    <a href='<?php echo $this->url(array('controller' => 'user','action'=>'add'));?>'>Add New User</a>
    
</div>

<div id="view-content">
    <table border="1">
      
        <tr>
        <th>ID</th>
        <th>Image </th>
		<th>Fistname</th>
		<th>Middlename</th>
		<th>Lastname</th>
		<th>Email</th>
        <th>Gender</th>
		<th>Signature</th>
		<th>Role</th>
		<th>Status</th>

		<th>Country</th>
              <th>Operations</th>
 
            <?php

            for ($i=0;$i<count($this->users); $i++) { 
        	echo "<tr>";
            

        	
        	echo "<td>".$this->users[$i]['uid']."</td>";
        	echo "<td>";
        	echo " <img src='http://localhost/zfproject/public/upload/".$this->users[$i]['photo']."' width=50 heigth=50 />";
        	echo "</td>";
            echo "<td>".$this->users[$i]['fname']."</td>";
            echo "<td>".$this->users[$i]['mname']."</td>";
            echo "<td>".$this->users[$i]['lname']."</td>";
            echo "<td>".$this->users[$i]['email']."</td>";
            
            
            echo "<td>".$this->users[$i]['gender']."</td>";
            echo "<td>".$this->users[$i]['signature']."</td>";
            echo "<td>".$this->users[$i]['role']."</td>";
            echo "<td>".$this->users[$i]['status']."</td>";
            
          		
   
            echo "<td>".$this->users[$i]['country']."</td>";
            
            //echo "<td><a href='   <?php echo $this->url(array('controller' => 'user','action'=>'add'));   edit/id/".$this->users[$i]['uid']."'>
            //		Edit</a><a href='delete/id/".$this->users[$i]['uid']."'> Delete</a></td>";
            
            echo "<td>";
            echo "<a href='http://localhost/zfproject/public/user/edit/id/".$this->users[$i]['uid']."'> Edit</a>";
            echo "<a href='http://localhost/zfproject/public/user/delete/id/".$this->users[$i]['uid']."'> Delete</a>";
            echo "</td>";
            
            
            echo "</tr>";
            }
       
            
        ?>
            
       
        
    </table>
</div>